---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-existence-checker
  labels:
    app: pod-existence-checker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-existence-checker-sa
  namespace: pod-existence-checker
  labels:
    app: pod-existence-checker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-existence-checker-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: pod-existence-checker-sa
  namespace: pod-existence-checker
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io